services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - C:\Users\c-est\AppData\Roaming\gcloud\application_default_credentials.json:/app/google_creds.json:ro
    environment:
      - VECTOR_DB_URL=${VECTOR_DB_URL}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_creds.json
    env_file:
      - .env
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE

volumes:
  chroma_data:
